### PR TITLE
UNSAFE_componentWillReceiveProps replaced in favor of getDerivedStateFromProps

### LINKED ISSUE #193: Warning: Using UNSAFE_componentWillReceiveProps in strict mode
## Description

Using react-slider generates a react warning in strict mode:

```
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: ReactSlider
```

> Issue seems to be located in `ReactSlider.js` line 388.

```
  _proto.UNSAFE_componentWillReceiveProps = function UNSAFE_componentWillReceiveProps(newProps) {
    var value = sanitizeInValue(newProps.value);

    if (!value.length) {
      // eslint-disable-next-line prefer-destructuring
      value = this.state.value;
    } // ensure the array keeps the same size as `value`


    this.tempArray = value.slice();

    for (var i = 0; i < value.length; i += 1) {
      this.state.value[i] = this.trimAlignValue(value[i], newProps);
    }

    if (this.state.value.length > value.length) {
      this.state.value.length = value.length;
    }
  };
```

### PR DESCRIPTION
**Pull request by Wmaileq**
This PR removes annoying warnings.

- Replaced deprecated method in favor of new one
- Added test coverage.
Closes #193

### CODE REVIEW

**Comment by stonebk** [comment]
@Wmaileq thanks for the contribution! The changes look good, can you just update the commit message to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) guidelines (for our changelog generation)? Something like this:

> refactor: UNSAFE_componentWillReceiveProps replaced in favor of getDerivedStateFromProps
>
> Fixes #193

**Comment by Wmaileq** [comment]
@stonebk Done!

**Comment by stonebk** [comment]
@Wmaileq sorry to nitpick, but can you make it lower-case "refactor:"? I'm worried that `standard-version` might be case sensitive on the types

**Comment by Wmaileq** [comment]
> @Wmaileq sorry to nitpick, but can you make it lower-case "refactor:"? I'm worried that `standard-version` might be case sensitive on the types

I thought about it too, but: https://www.conventionalcommits.org/en/v1.0.0/#specification (15)
But i will rename for consistency
@stonebk Done!

**Comment by Wmaileq** [comment]
But i will rename for consistency

**Comment by stonebk** [comment]
Good to know, thanks!

**Comment by stonebk** [comment]
`react-slider@1.0.10`

**Comment by stonebk** [comment]
Had to revert this change due to https://github.com/zillow/react-slider/issues/197

Started working on a solution, but it needs some more thought:
https://github.com/zillow/react-slider/pull/198

**Pull request merged**
