### PR TITLE
Hey maintainers 👋, here are a bunch of contributions 🎉

### PR DESCRIPTION
**Pull request by stonebk**
Hi there, I've used your react-slider component on a couple projects. It's the only CSS agnostic React slider that I am aware of, and I love it for that.

I wanted to use your component as the basis for our new slider component at Zillow, but there are a number of bugs and accessibility issues that I was looking to resolve first. I went ahead and forked your repository and made a lot of changes that I would like to contribute back.

There are a lot of changes in this PR -- fixes for existing issues, fixes for new issues I found during my accessibility and cross-browser testing, and new features that I think make the component much more flexible. Hopefully you will want to take most of the changes, but I understand some of them might be a little more controversial (i.e. renaming "handle" and "bar" to "thumb" and "track"). I wanted to at least start the conversation and contribute back whatever I can.

Thanks!
Brian

In the meantime, I've published a fork of the project:
https://www.npmjs.com/package/@zillowgroup/react-slider

Here is the new generated documentation:
https://zillow.github.io/react-slider/

Here is a list of existing Issues and Pull requests this PR could address in some way:
* #127 (create-react-class has been removed entirely)
* #126 (moved to new modern tooling with a dev site)
* #120 (create-react-class has been removed entirely)
* #81 (render props now give you full flexibility over slider nodes)
* #59 (children have been removed altogether in favor of render props)
* #144 (my other PR)
* #135 (another take on improving the developer experience)
* #110 (render props pass value state to the function)
* #82 (can be achieved with render props and state)

Here is a look at my changes taken straight from the new generated [CHANGELOG](https://github.com/zillow/react-slider/blob/HEAD/CHANGELOG.md):

### Bug Fixes

* add IE11 arrow key support ([39f6ae1](https://github.com/zillow/react-slider/commit/39f6ae1))
* do nothing when right clicking on the slider ([c7fd64f](https://github.com/zillow/react-slider/commit/c7fd64f))
* Home and End keys no longer scroll the page when setting the value ([fff37d5](https://github.com/zillow/react-slider/commit/fff37d5))
* remove active state on thumb on blur ([64d928a](https://github.com/zillow/react-slider/commit/64d928a))
* the active thumb should get focus when a value is selected ([b5d2115](https://github.com/zillow/react-slider/commit/b5d2115))

### Code Refactoring

* remove support for custom thumbs via `children` ([05bf77c](https://github.com/zillow/react-slider/commit/05bf77c))

### Features

* remove dependency on create-react-class ([ae214a2](https://github.com/zillow/react-slider/commit/ae214a2))
* add `renderHandle` render prop for dynamic handle content ([3cea501](https://github.com/zillow/react-slider/commit/3cea501))
* add `renderBar` render prop for customizing bar content ([2969f5e](https://github.com/zillow/react-slider/commit/2969f5e))
* "handle" and "bar" are now "thumb" and "track" to follow `input[type=range]` nomenclature ([b7d18ea](https://github.com/zillow/react-slider/commit/b7d18ea))
* `ariaValuetext` now supports a function for dynamic value text ([706b275](https://github.com/zillow/react-slider/commit/706b275))
* `renderThumb` now renders the entire thumb node rather than just the thumb content ([04f3285](https://github.com/zillow/react-slider/commit/04f3285))
* `withTracks` is now true by default ([02a4bf3](https://github.com/zillow/react-slider/commit/02a4bf3))
* add `valueNow` to state objects of `ariaValuetext` and `renderThumb` for easier access to the current value ([08aa273](https://github.com/zillow/react-slider/commit/08aa273))
* add aria-orientation to slider ([714da9f](https://github.com/zillow/react-slider/commit/714da9f))
* add support for Page Up and Page Down keys ([7b9f536](https://github.com/zillow/react-slider/commit/7b9f536))
* pass `value` state to render props ([d42545e](https://github.com/zillow/react-slider/commit/d42545e))
* the paging value is now configurable via the `pageFn` prop ([a54021e](https://github.com/zillow/react-slider/commit/a54021e))

### BREAKING CHANGES

* The render props `renderThumb` and `renderTrack` are now passed two arguments
instead of one, `props` and `state`. This makes it easier to just spread props when using
a render function.
* `renderThumb` was previously given the indexed handle value
which now needs to be derived from `value` and `index.
* custom thumbs via `children` is no longer supported.
To customize thumbs, use the `renderThumb` render prop instead.
* `withTracks` is more commonly true than false,
so we are making that the default
* "handle" and "bar" props have been renamed to "thumb" and "track",
e.g. `withBars` is now `withTracks`, and `handleClassName` is now `thumbClassName`

### CODE REVIEW

**Comment by hinok** [comment]
@stonebk Great work! I also use `react-slider` in my project.
@mpowaga Could you check this PR and merge it?

**Comment by ivansky** [comment]
Hey @mpowaga if you are not gonna work on this library anymore would you mind to give someone access to it who can keep it up-to-date. Thanks!

**Comment by mpowaga** [comment]
@stonebk Nice work! I'm happy to merge this PR and give you an access to the repo. Another option would be to close this repo and redirect users to zillow/react-slider. Let me know what do you think is the best option.

**Comment by stonebk** [comment]
> @stonebk Nice work! I'm happy to merge this PR and give you an access to the repo. Another option would be to close this repo and redirect users to zillow/react-slider. Let me know what do you think is the best option.

Thanks @mpowaga! If you are no longer interested in maintaining the project, rather than closing the repo, you could just transfer ownership to the [Zillow organization](https://github.com/zillow) and we would be happy to maintain it!

If you'd prefer to keep ownership (totally understandable, you've put a lot of hard work into this project), then we can continue to maintain our fork which you could point to. We can continue to upstream our changes which you could publish, or you could give us access to the unscoped package on npm and we could start publishing from the fork.

Let me know how you want to proceed! And thanks again for the great component :)

**Comment by mpowaga** [comment]
@stonebk I think the best option will be to transfer ownership. However it seems that you need to rename the fork repository and temporarily grant me an access to zillow organization because I receive following error.

`zillow/react-slider already exists and You don’t have the permission to create public repositories on zillow`

**Comment by stonebk** [comment]
@mpowaga can you just add me as an owner here and then I can do the juggling?

**Comment by stonebk** [comment]
Shoot, doesn't look like I can do anything as a collaborator.

> Transfer this repository to another user or to an organization where you have the ability to create repositories.

I think if you transfer ownership to me, then I can transfer it to the zillow organization since I have write access there.

**Comment by stonebk** [comment]
🎉Success 🎉 

Tomorrow I'll work on cleaning up this PR (removing extraneous version commits), and pushing out a new major version!

@mpowaga, I think you'll still need to grant the [zillowgroup organization](https://www.npmjs.com/org/zillowgroup) access to the NPM project for publishing. Here is what I found: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-an-org

Thanks again!

**Comment by mpowaga** [comment]
@stonebk With the npm package we need to do the same, i.e. first transfer it to you then you can add it to your organization. Can you send me your npm handle?

**Comment by stonebk** [comment]
Same name! https://www.npmjs.com/~stonebk

**Comment by stonebk** [comment]
Clean up work taking place in #147

**Comment by stonebk** [comment]
`react-slider@1.0.0` published 🎉 

Thanks again @mpowaga!

**Pull request closed without merging**
