### PR TITLE
Step function for non linear values

### PR DESCRIPTION
**Pull request by veloce**

### CODE REVIEW

**Comment by mehiel** [comment]
This is actually really interesting. We could probably implement something like `rc-slider`'s marks on top of it.

No interest on merging?

**Comment by jamesbrauman** [comment]
@mehiel Could you let me know in what circumstances something like this could be useful?

**Comment by davidpellerin** [comment]
This is indeed very interesting.  I can imagine this being used on sliders which involve currency.  Sometimes the majority end-users want to choose a price that is more on the low end, and a small amount of users want to choose larger number (examples: prices of houses, jewelry, etc..).  A way of displaying the values in a logarithmic scale would be awesome.  I'll pull down this branch and test and give some feedback.

**Comment by mehiel** [comment]
@jamesbrauman seems like I missed the notification on your message. The truth is that for what I wanted this didn't prove useful - I needed a slider with snapping and marks. So I used `react-slider` but I implemented the marking feature in a custom manner by wrapping it in another component.

But the case @davidpellerin describes has value as well. It may be an edge case but makes sense.

**Pull request closed without merging**
